name: Deploy to Azure

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: |
        cd src
        go build -o ../handler.exe
        cd ..
    - name: Deploy
      uses: Azure/functions-action@v1
      with:
        app-name: ephemeral-twitter
        package: '.'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-funcignore: true